apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-vsanchez
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /dev-vsanchez
        pathType: Prefix
        backend:
          service:
            name: frontend-develop-svc
            port:
              number: 80
      - path: /prod-vsanchez
        pathType: Prefix
        backend:
          service:
            name: frontend-production-svc
            port:
              number: 80
