
frontend:
  replicas: 2
  image: containerregistryvsanchez.azurecr.io/imagen-proyecto-frontend:0.1.3
  containerPort: 80
  resources:
    requests:
      memory: "128Mi"
      cpu: "250m"
    limits:
      memory: "256Mi"
      cpu: "500m"
  service:
    port: 80
    type: LoadBalancer

ingress:
  enabled: true
  host: frontend
  annotations:
    path: /
  tls: true
  tlsSecretName: example-tls-secret