name: CI
on:
  workflow_dispatch:

jobs:
  echoSecrets:
    runs-on: ubuntu-latest
    steps:
      - name: Echo secrets
        run: |
          echo CLIENT_ID: "${{ secrets.ARM_CLIENT_ID }}"
          echo CLIENT_SECRET: "${{ secrets.ARM_CLIENT_SECRET }}"
          echo TENANT_ID: "${{ secrets.ARM_TENANT_ID }}"
          echo SUBSCRIPTION_ID: "${{ secrets.ARM_SUBSCRIPTION_ID }}"
          
  subirDocker:
    uses: stemdo-labs/final-project-exercise-ValentinoSanchez00/.github/workflows/SubirDockerfiles.yaml@main
    secrets: 
       ARM_CLIENT_ID: "${{ secrets.ARM_CLIENT_ID }}"
       ARM_CLIENT_SECRET: "${{ secrets.ARM_CLIENT_SECRET }}"
       ARM_TENANT_ID: "${{ secrets.ARM_TENANT_ID }}"
       ARM_SUBSCRIPTION_ID: "${{ secrets.ARM_SUBSCRIPTION_ID }}"
    with: 
      VERSION_CHART: "0.1.0" # Versión del Chart
      MICROSERVICE: "frontend" # Nombre del microservicio 
     
      
  subirCharts:
    uses: stemdo-labs/final-project-exercise-ValentinoSanchez00/.github/workflows/subirCharts.yaml@main
    with:
      VERSION_CHART: "0.1.0" # Versión del Chart
      MICROSERVICE: "frontend" # Nombre del microservicio
