name: Subir Chart
on:
  workflow_dispatch:
    inputs:
      MICROSERVICE:
        description: 'Nombre del microservicio'
        required: true
        default: 'frontend'
jobs:
  subirCharts:
    uses: stemdo-labs/final-project-exercise-ValentinoSanchez00/.github/workflows/SubirCharts.yaml@main
    secrets:
      TOKEN_GITHUB: "${{ secrets.TOKEN_GITHUB }}"
      HARBOR_PASSWORD: "${{ secrets.HARBOR_PASSWORD }}"
    with:
      MICROSERVICE: "${{ inputs.MICROSERVICE }}"