name: Subir Dockerfile
on:
  push:
    branches:
      - main

jobs:
  subirDocker:
    uses: stemdo-labs/final-project-exercise-ValentinoSanchez00/.github/workflows/SubirDockerfiles.yaml@main
    with:
      MICROSERVICE: "frontend"
    secrets: inherit


