name: Subir Dockerfile
on:
  push:
    branches:
      - main

jobs:
  subirDocker:
    uses: stemdo-labs/final-project-exercise-ValentinoSanchez00/.github/workflows/SubirDockerfiles.yaml@main
    with:
      MICROSERVICE: "frontend"
    secrets: inherit

  realizarCD:
    needs: subirDocker
    uses: ./.github/workflows/principal.yaml
    with:
      MICROSERVICE: "frontend"
      VERSION_CHART: "0.2.1"
    secrets: inherit
