name: Subir Dockerfile
on:
  workflow_dispatch:
    inputs:
      MICROSERVICE:
        description: 'Nombre del microservicio'
        required: true
        default: 'frontend'

jobs:         
  subirDocker:
    uses: stemdo-labs/final-project-exercise-ValentinoSanchez00/.github/workflows/SubirDockerfiles.yaml@develop
    secrets: 
       ARM_CLIENT_ID: "${{ secrets.ARM_CLIENT_ID }}"
       ARM_CLIENT_SECRET: "${{ secrets.ARM_CLIENT_SECRET }}"
       ARM_TENANT_ID: "${{ secrets.ARM_TENANT_ID }}"
       ARM_SUBSCRIPTION_ID: "${{ secrets.ARM_SUBSCRIPTION_ID }}"
    with:  
      MICROSERVICE: "${{ inputs.MICROSERVICE }}" # Nombre del microservicio 
     
    
    

