name: Subir Dockerfile
on:
 push:
   branches:
     - main

jobs:         
  subirDocker:
    uses: stemdo-labs/final-project-exercise-ValentinoSanchez00/.github/workflows/SubirDockerfiles.yaml@main
    secrets: 
       ARM_CLIENT_ID: "${{ secrets.ARM_CLIENT_ID }}"
       ARM_CLIENT_SECRET: "${{ secrets.ARM_CLIENT_SECRET }}"
       ARM_TENANT_ID: "${{ secrets.ARM_TENANT_ID }}"
       ARM_SUBSCRIPTION_ID: "${{ secrets.ARM_SUBSCRIPTION_ID }}"
    with:  
      MICROSERVICE: "frontend" 
  flujoCD:
    needs: subirDocker
    uses: ./.github/workflows/principal.yaml
    secrets: 
       ARM_CLIENT_ID: "${{ secrets.ARM_CLIENT_ID }}"
       ARM_CLIENT_SECRET: "${{ secrets.ARM_CLIENT_SECRET }}"
       ARM_TENANT_ID: "${{ secrets.ARM_TENANT_ID }}"
       ARM_SUBSCRIPTION_ID: "${{ secrets.ARM_SUBSCRIPTION_ID }}"
       HARBOR_PASSWORD: "${{ secrets.HARBOR_PASSWORD }}"
    with:  
      MICROSERVICE: "frontend" 
      VERSION_CHART: "0.2.1"

     
    
    

